package:
  name: pylinac
  version: "1.5.6"

source:
  fn: pylinac-1.5.6.zip
#  url: https://pypi.python.org/packages/source/p/pylinac/pylinac-1.5.6.zip
  url: https://pypi.python.org/packages/09/cd/2929342633b7f4a02aaf69861536c654dfb129ea3614013a16caf432009d/pylinac-1.5.6.zip
  md5: f7ceee14e4aae7e2401221ed05aa9944

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - pylinac = pylinac.scripts:cli
    #
    # Would create an entry point called pylinac that calls pylinac.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy >=0.15
    - pydicom >=0.9.9
    - matplotlib >=1.3.1
    - scikit-image >=0.11
    - pillow >=2.5
    - dask  # completely unknown why this is needed, but it fails w/o it
    - tqdm

  run:
    - python
    - numpy >=1.9
    - scipy >=0.15
    - pydicom >=0.9.9
    - matplotlib >=1.3.1
    - scikit-image >=0.11
    - pillow >=2.5
    - tqdm

#test:
  # Python imports
#  imports:
#    - pylinac
#    - pylinac.core

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jrkerns/pylinac
  license: MIT License
  summary: 'A toolkit for performing TG-142 QA-related tasks on a linear accelerator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
