package:
  name: pylinac
  version: "1.7.2"

source:
  fn: pylinac-1.7.2.zip
  url: https://pypi.python.org/packages/db/0d/d2792369ab6f4f6c6ad9b459cafd9b63a407ac173a9ccc47f403ee368636/pylinac-1.7.2.zip#md5=a5bb90019bbffe3f47bb691c77b3e693
  md5: a5bb90019bbffe3f47bb691c77b3e693

#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    - pylinac = pylinac.scripts:cli
    #
    # Would create an entry point called pylinac that calls pylinac.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.9
    - scipy >=0.15
    - pydicom >=0.9.9
    - matplotlib >=1.3.1
    - scikit-image >=0.11
    - scikit-learn >=0.17
    - pillow >=2.5
    - dask  # completely unknown why this is needed, but it fails w/o it
    - tqdm ==3.8.0
    - mpld3
    - click
    - yagmail >=0.5.147
    - pyyaml

  run:
    - python
    - numpy >=1.9
    - scipy >=0.15
    - pydicom >=0.9.9
    - matplotlib >=1.3.1
    - scikit-image >=0.11
    - scikit-learn >=0.17
    - pillow >=2.5
    - tqdm
    - mpld3
    - click
    - yagmail
    - pyyaml

#test:
  # Python imports
#  imports:
#    - pylinac
#    - pylinac.core

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jrkerns/pylinac
  license: MIT License
  summary: 'A toolkit for performing TG-142 QA-related tasks on a linear accelerator'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
